---
title: "Analysis -- priming lexicalisation patterns in L2"
author: "Guillermo Montero-Melis"
date: "Thursday, January 19, 2017"
output: pdf_document
---

```{r}
library(dplyr)
library(ggplot2)
library(lazyeval)

```



```{r, echo=FALSE}


#  ------------------------------------------------------------------------
#  Load data and process
#  ------------------------------------------------------------------------

# The data is created in the script "processing/compute_dependent_measures.R"
# There is the normal and the liberally coded version, see script for difference

# load
d <- read.csv("../data/data_DVs.csv", fileEncoding = "UTF-8", stringsAsFactors = FALSE)
head(d)
# adjust Condition and Group levels for plotting
d$Condition <- factor(d$Condition, levels = c("Path", "Control", "Manner"))
d$Group <- factor(d$Group, levels = c("NS", "L2"))

# participant data
ppts <- read.csv("../data/participants.csv", fileEncoding = "UTF-8", stringsAsFactors = FALSE)
head(ppts)

# add speakers' clozescore to d:
d <- left_join(d, ppts %>% select(Subject, ClozeScore))
head(d)
tail(d)



#  ------------------------------------------------------------------------
#  Functions
#  ------------------------------------------------------------------------


# Convenience function to compute by-speaker averages for a given variable
bysubj <- function(df, myvar = NULL, varname = NULL) {
  out <- df %>% 
    group_by(Subject, Group, Condition, ClozeScore) %>%
    # to pass variable name as a string, use standard evaluation, see
    # https://cran.r-project.org/web/packages/dplyr/vignettes/nse.html
    # (NB: I don't get how this is working, but seems to work)
    summarise_(M = interp(~ mean(var), var = as.name(myvar)))
  # if varname argument is supplied it names the computed column
  if (! is.null(varname)) names(out)[length(out)] <- varname
  out
}
bysubj(d, "P_anyw") %>% head
bysubj(d, "P_anyw", "P_anyw") %>% head


## plotting functions

# plot group patterns -- emphasis put between conditions in each group
f_plot <- function(df, varname = NULL) {
  p <- ggplot(df, aes(x = Group, y = M, colour = Condition)) +
    geom_point(position = position_jitterdodge()) +
    stat_summary(fun.data = mean_cl_boot, geom = "errorbar", size = .85, width = .5,
                 position = "dodge") +
    ylim(0,1) +
    ylab(paste("Proportion of descriptions\nexpressing", varname)) + 
    ggtitle(varname)
  p
}

# f_plot2 <- function(df, varname = NULL) {
#   p <- ggplot(df, aes(x = Condition, y = M, colour = Group)) +
#     geom_point(position = position_jitterdodge()) +
#     stat_summary(fun.data = mean_cl_boot, geom = "errorbar", size = .85, width = .5,
#                  position = "dodge") +
#     ggtitle(varname)
#   p
# }


# Plot effect of proficiency (cloze score)
f_plot_prof <- function(df, varname = NULL) {
  df <- df[df$Group == "L2", ]
  p <- ggplot(df, aes(x = ClozeScore, y = M, colour = Condition)) +
    geom_jitter(height = 0) +
    geom_smooth(method = "lm") +
    # ylim(0,1) +
    ylab(paste("Proportion of descriptions\nexpressing", varname)) + 
    ggtitle(varname)
  p
}


#  ------------------------------------------------------------------------
#  Plots
#  ------------------------------------------------------------------------

# group patterns
f_plot(bysubj(d, "P_anyw"), "Path anywhere")
f_plot(bysubj(d, "P_V"), "Path in V")
f_plot(bysubj(d, "P_adj"), "Path in adjunct")

f_plot(bysubj(d, "M_anyw"), "Manner anywhere")
f_plot(bysubj(d, "M_V"), "Manner in V")
f_plot(bysubj(d, "M_adj"), "Manner in adjunct")

# proficiency
f_plot_prof(bysubj(d, "P_anyw"), "Path anywhere")
f_plot_prof(bysubj(d, "P_V"), "Path in V")
f_plot_prof(bysubj(d, "P_adj"), "Path in adjunct")

f_plot_prof(bysubj(d, "M_anyw"), "Manner anywhere")
f_plot_prof(bysubj(d, "M_V"), "Manner in V")
f_plot_prof(bysubj(d, "M_adj"), "Manner in adjunct")

```

